### ISSUE TITLE
Add User Name

### ISSUE THREAD

**Issue by brunocalado** [TheMasterGeese/Discord-Integration#19]
Hi

Can you add the playername/token name to the discord message?
![image](https://user-images.githubusercontent.com/4999783/177566348-f5be7a2f-435c-436b-bde0-634b765b4034.png)

**Comment by TheMasterGeese** [comment]
Issue #11 will cover pinging based on token name, Are you looking to automatically add the Player/Token Name to any message that will ping them?

**Comment by brunocalado** [comment]
> Issue #11 will cover pinging based on token name, Are you looking to automatically add the Player/Token Name to any message that will ping them?

I was thinking about the discord message from foundry vtt be like that:
The Foundry VTT Player **BobFire** types on foundry chat: **I'll die**.
The discord shows: **BobFire**: **I'll die**

**Comment by TheMasterGeese** [comment]
Pull request into v2.2.0 completed, will be a part of the next release.
