### ISSUE TITLE
Player Image Replace Discord Bot Image

### ISSUE THREAD

**Issue by brunocalado** [TheMasterGeese/Discord-Integration#20]
Hi.

Can you make the discord bot image (webhook) show the player image instead of the default webhook image?

tks

**Comment by TheMasterGeese** [comment]
While Discord does support using custom images as the avatar when sending messages via webhook, it requires an image URL to do so. FoundryVTT requires any chat avatars to be uploaded, thus any URLs given via the webhook would be relative to the local filesystem, and would not be retrievable by Discord. I may consider implementing a mod that uploads chat avatar images elsewhere and then send the link that way if there's interest, but for now I'm closing this issue.
