### ISSUE TITLE
Button Press to Toggle the Mod On/Off

### ISSUE THREAD

**Issue by kunsumii** [TheMasterGeese/Discord-Integration#23]
Suggesting a button you can press from the left-hand control buttons to turn the mod on and off. 

![yBDnkFK](https://user-images.githubusercontent.com/105966577/178160629-60e55f69-62d2-49ac-8dc0-de9f127f06e8.png)

**Comment by TheMasterGeese** [comment]
Feature implemented, will be part of Version v2.2.0.
