### ISSUE TITLE
Installation failed: ... discord-integration.zip: Not Found

### ISSUE THREAD

**Issue by Avera9eJoe** [TheMasterGeese/Discord-Integration#39]
I'm a new user to FoundryVTT doing first-time setup for a game, and I am unable to install `Discord Management Library` from the Install Module menu. When I try, I am greeted with this error:

`Installation failed: An unexpected error occurred when downloading file https://github.com/TheMasterGeese/discord-integration/main/bundle/discord-integration.zip: not found`

How do I fix this so I can install?

**Comment by Avera9eJoe** [comment]
An update, I think I succeeded in manually installing? I downloaded the ZIP myself and placed it inside of `C:\Users\HafCo\AppData\Local\FoundryVTT\Data\modules`, and upon repeating my steps to try and give you a list of what I did, show where it went wrong, it now shows as being installed.

**Comment by TheMasterGeese** [comment]
Found and fixed the issue, released v2.1.6 to hotfix it. Let me know if you have any other issues.
