### ISSUE TITLE
Option: Don't pass on messages that start with "/" (generally commands)

### ISSUE THREAD

**Issue by Sayshal** [TheMasterGeese/Discord-Integration#54]
The title explains it all. Currently, the feature to pass on all messages (which is amazing, thank you) also passes on commands. Some users (me) may want those commands hidden.

![1NAaT6A](https://user-images.githubusercontent.com/117966309/204387625-8d3b3412-b50a-41ad-8083-c5570f2ff2a0.png)

**Comment by Nedrapter** [comment]
Ideally I'd say if this module allows everything that goes on the chat to be forwarded to discord, a tickbox list with what is allowed to be forwarded would work perfect!

**Comment by Sayshal** [comment]
Hope to see this soon - I've had to stop using this module because whispers aren't secret anymore but having a discord log of our messages was useful.
